import { IProductFilter } from '../types/product.interface';
export const filterProperty: IProductFilter = {
  category: [
    { name: 'smartphones', current: 0, max: 5 },
    { name: 'laptops', current: 0, max: 5 },
    { name: 'fragrances', current: 0, max: 5 },
    { name: 'skincare', current: 0, max: 5 },
    { name: 'groceries', current: 0, max: 5 },
    { name: 'home-decoration', current: 0, max: 5 },
    { name: 'furniture', current: 0, max: 5 },
    { name: 'tops', current: 0, max: 5 },
    { name: 'womens-dresses', current: 0, max: 5 },
    { name: 'womens-shoes', current: 0, max: 5 },
    { name: 'mens-shirts', current: 0, max: 5 },
    { name: 'mens-shoes', current: 0, max: 5 },
    { name: 'mens-watches', current: 0, max: 5 },
    { name: 'womens-watches', current: 0, max: 5 },
    { name: 'womens-bags', current: 0, max: 5 },
    { name: 'womens-jewellery', current: 0, max: 5 },
    { name: 'sunglasses', current: 0, max: 5 },
    { name: 'automotive', current: 0, max: 5 },
    { name: 'motorcycle', current: 0, max: 5 },
    { name: 'lighting', current: 0, max: 5 },
  ],
  brand: [
    { name: 'Apple', current: 0, max: 3 },
    { name: 'Samsung', current: 0, max: 2 },
    { name: 'OPPO', current: 0, max: 1 },
    { name: 'Huawei', current: 0, max: 1 },
    { name: `Microsoft Surface`, current: 0, max: 1 },
    { name: 'Infinix', current: 0, max: 1 },
    { name: 'HP Pavilion', current: 0, max: 1 },
    { name: 'Impression of Acqua Di Gio', current: 0, max: 1 },
    { name: 'Royal_Mirage', current: 0, max: 1 },
    { name: 'Fog Scent Xpressio', current: 0, max: 1 },
    { name: 'Al Munakh', current: 0, max: 1 },
    { name: 'Lord - Al-Rehab', current: 0, max: 1 },
    { name: `L'Oreal Paris`, current: 0, max: 1 },
    { name: 'Hemani Tea', current: 0, max: 1 },
    { name: 'Dermive', current: 0, max: 1 },
    { name: 'ROREC White Rice', current: 0, max: 1 },
    { name: 'Fair & Clear', current: 0, max: 1 },
    { name: 'Saaf & Khaas', current: 0, max: 1 },
    { name: 'Bake Parlor Big', current: 0, max: 1 },
    { name: 'Baking Food Items', current: 0, max: 1 },
    { name: 'fauji', current: 0, max: 1 },
    { name: 'Dry Rose', current: 0, max: 1 },
    { name: 'Boho Decor', current: 0, max: 1 },
    { name: 'Flying Wooden', current: 0, max: 1 },
    { name: 'LED Lights', current: 0, max: 1 },
    { name: 'luxury palace', current: 0, max: 1 },
    { name: 'Golden', current: 0, max: 1 },
    { name: 'Furniture Bed Set', current: 0, max: 1 },
    { name: 'Ratttan Outdoor', current: 0, max: 1 },
    { name: 'Kitchen Shelf', current: 0, max: 1 },
    { name: 'Multi Purpose', current: 0, max: 1 },
    { name: 'AmnaMart', current: 0, max: 1 },
    { name: 'Professional Wear', current: 0, max: 1 },
    { name: 'Soft Cotton', current: 0, max: 2 },
    { name: 'Top Sweater', current: 0, max: 2 },
    { name: 'RED MICKY MOUSE..', current: 0, max: 1 },
    { name: 'Digital Printed', current: 0, max: 1 },
    { name: 'Ghazi Fabric', current: 0, max: 2 },
    { name: 'IELGY', current: 0, max: 1 },
    { name: 'IELGY fashion', current: 0, max: 1 },
    { name: 'Synthetic Leather', current: 0, max: 1 },
    { name: 'Sandals Flip Flops', current: 0, max: 1 },
    { name: 'Maasai Sandals', current: 0, max: 1 },
    { name: 'Arrivals Genuine', current: 0, max: 1 },
    { name: 'Vintage Apparel', current: 0, max: 2 },
    { name: 'FREE FIRE', current: 0, max: 1 },
    { name: 'The Warehouse', current: 0, max: 3 },
    { name: 'Sneakers', current: 0, max: 3 },
    { name: 'Rubber', current: 0, max: 1 },
    { name: 'Naviforce', current: 0, max: 1 },
    { name: 'SKMEI 9117', current: 0, max: 2 },
    { name: 'Strap Skeleton', current: 0, max: 1 },
    { name: 'Stainless', current: 0, max: 1 },
    { name: 'Eastern Watches', current: 0, max: 2 },
    { name: 'Luxury Digital', current: 0, max: 1 },
    { name: 'Watch Pearls', current: 0, max: 1 },
    { name: 'Bracelet', current: 0, max: 2 },
    { name: 'LouisWill', current: 0, max: 3 },
    { name: 'Copenhagen Luxe', current: 0, max: 2 },
    { name: 'Steal Frame', current: 0, max: 1 },
    { name: 'Darojay', current: 0, max: 1 },
    { name: 'Fashion Jewellery', current: 0, max: 2 },
    { name: 'Cuff Butterfly', current: 0, max: 1 },
    { name: 'Designer Sun Glasses', current: 0, max: 2 },
    { name: 'mastar watch', current: 0, max: 2 },
    { name: 'Car Aux', current: 0, max: 1 },
    { name: 'W1209 DC12V', current: 0, max: 1 },
    { name: 'TC Reusable', current: 0, max: 2 },
    { name: 'Neon LED Light', current: 0, max: 1 },
    { name: 'METRO 70cc Motorcycle - MR70', current: 0, max: 1 },
    { name: 'BRAVE BULL', current: 0, max: 1 },
    { name: 'shock absorber', current: 0, max: 1 },
    { name: 'JIEPOLLY', current: 0, max: 1 },
    { name: 'Xiangle', current: 0, max: 1 },
    { name: 'lightingbrilliance', current: 0, max: 1 },
    { name: 'Ifei Home', current: 0, max: 2 },
    { name: 'DADAWU', current: 0, max: 1 },
    { name: 'YIOSI', current: 0, max: 1 },
  ],
  price: {
    currentMin: 10,
    currentMax: 1749,
    min: 10,
    max: 1749,
  },
  stock: {
    currentMin: 2,
    currentMax: 150,
    min: 2,
    max: 150,
  },
};

export default filterProperty;
